name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: $current_repo_owner
          base: master
          head: master
